package com.owo233.tcqt

import android.app.Application
import com.owo233.tcqt.data.TCQTBuild
import com.owo233.tcqt.ext.ActionProcess
import com.owo233.tcqt.ext.IAction
import com.owo233.tcqt.generated.GeneratedActionList
import com.owo233.tcqt.generated.GeneratedFeaturesData
import com.owo233.tcqt.generated.GeneratedSettingList
import com.owo233.tcqt.utils.dexkit.DexKitTask
import com.owo233.tcqt.utils.log.Log
import com.owo233.tcqt.utils.reflect.getObject
import com.owo233.tcqt.utils.reflect.new

internal object ActionManager {

    private val FIRST_ACTION = GeneratedActionList.ACTIONS // generated by KSP

    private val instanceMap = hashMapOf<Class<out IAction>, IAction>()

    private val failedActions = hashSetOf<Class<out IAction>>()

    private fun instanceOf(cls: Class<out IAction>): IAction? {
        if (cls in failedActions) return null

        return runCatching {
            instanceMap.getOrPut(cls) {
                try {
                    cls.getObject("INSTANCE") as IAction
                } catch (_: NoSuchFieldException) {
                    cls.new()
                }
            }
        }.getOrElse { e ->
            Log.e("ActionManager instanceOf failed", e)
            failedActions.add(cls)
            null
        }
    }

    fun runFirst(
        app: Application,
        proc: ActionProcess,
        excludeDexKitTask: Boolean = false
    ) {
        val baseProcs = setOf(
            ActionProcess.MSF,
            ActionProcess.MAIN,
            ActionProcess.TOOL,
            ActionProcess.OPENSDK,
            ActionProcess.QZONE,
            ActionProcess.QQFAV
        )

        FIRST_ACTION.forEach { actionClass ->
            if (excludeDexKitTask && DexKitTask::class.java.isAssignableFrom(actionClass)) {
                return@forEach
            }

            runCatching {
                val action = instanceOf(actionClass) ?: run {
                    if (TCQTBuild.DEBUG) {
                        Log.e("instanceOf [${actionClass.simpleName}] failed")
                    }
                    return@forEach
                }

                val shouldRun =
                    ActionProcess.ALL in action.processes ||
                            proc in action.processes ||
                            (ActionProcess.OTHER in action.processes && proc !in baseProcs)

                if (shouldRun) {
                    action(app, proc)
                }
            }.onFailure { e ->
                throw RuntimeException(e)
            }
        }
    }

    fun getEnabledActionCount(): Int {
        return GeneratedFeaturesData.FEATURES.count {
            GeneratedSettingList.getBoolean(it.key)
        }
    }

    fun getDisabledActionCount(): Int {
        return GeneratedFeaturesData.FEATURES.count {
            !GeneratedSettingList.getBoolean(it.key)
        }
    }

    fun resolve(action: IAction): String {
        if (action.key.isBlank()) {
            return action::class.simpleName ?: "Unknown"
        }

        return GeneratedActionList.ACTION_NAME_MAP[action.key]
            ?: action.key
    }
}
