package com.qzone.reborn.feedpro.itemview;

public enum QzoneFeedProType {
    // 基础类型 (0-20)
    UNIQUE_TYPE_UNKNOWN(0),
    UNIQUE_TYPE_TEXT_FEED(1),
    UNIQUE_TYPE_SINGLE_VIDEO_FEED(2),
    UNIQUE_TYPE_MIX_PIC_VIDEO_FEED(3),
    UNIQUE_TYPE_BLOG(4),
    UNIQUE_TYPE_HAND_BLOG_FEED(5),
    UNIQUE_TYPE_FORWARD_TEXT_FEED(6),
    UNIQUE_TYPE_FORWARD_SINGLE_VIDEO_FEED(7),
    UNIQUE_TYPE_FORWARD_MIX_PIC_VIDEO_FEED(8),
    UNIQUE_TYPE_FORWARD_BLOG(9),
    UNIQUE_TYPE_FORWARD_HAND_BLOG_FEED(10),
    UNIQUE_TYPE_REPRINTED_TEXT_BLOG_FEED(11),
    UNIQUE_TYPE_MEMORY_SEAL(12),
    UNIQUE_TYPE_GUEST_MEMORY_SEAL(13),
    UNIQUE_TYPE_TIMELINE_EMPTY(14),
    UNIQUE_TYPE_FAVORITE_SHARE(15),
    UNIQUE_TYPE_REEDIT(16),
    UNIQUE_TYPE_LEFT_PIC_RIGHT_TEXT_SHARE(17),
    UNIQUE_TYPE_BIG_PIC_SHARE(18),
    UNIQUE_TYPE_GENERAL_BIG_CARD(19),
    UNIQUE_TYPE_INVALID(20),

    // 推荐/领域相关 (21-28)
    UNIQUE_TYPE_DOMAIN_RECO(21),
    UNIQUE_TYPE_DOMAIN_RECO_V2(22),
    UNIQUE_TYPE_DETAIL_ARCHIVE_TIPS(23),
    UNIQUE_TYPE_DOMAIN_RECO_TEXT(24),
    UNIQUE_TYPE_CONTRIBUTE(25),
    UNIQUE_TYPE_FORWARD_AD_MIX_PIC_VIDEO_FEED(26),
    UNIQUE_TYPE_GROUP_NAME(27),
    UNIQUE_TYPE_DOMAIN_RECO_MIX_SPLIT(28),

    // 广告类型 (1001-1010)
    UNIQUE_TYPE_AD_FEED(1001),
    UNIQUE_TYPE_AD_CARD_FEED(1002),
    UNIQUE_TYPE_AD_MULTI_PIC_FEED(1003),
    UNIQUE_TYPE_AD_CARD_MULTI_PIC_FEED(1004),
    UNIQUE_TYPE_AD_CONTRACT_FULL_FRAME_FEED(1005),
    UNIQUE_TYPE_AD_CONTRACT_CARD_FEED(1006),
    UNIQUE_TYPE_AD_CONTRACT_FULL_FRAME_GESTURE_FEED(1007),
    UNIQUE_TYPE_AD__RECOMMEND_PRO_FEED(1008),
    UNIQUE_TYPE_AD_CAROUSEL_CARD_FEED(1009),
    UNIQUE_TYPE_AD__RECOMMEND_PRO_V2_FEED(1010),

    // 隐藏类型
    UNIQUE_TYPE_HIDE(404);

    private int mViewType;

    QzoneFeedProType(int mViewType) {
        this.mViewType = mViewType;
    }

    public int getMViewType() {
        return this.mViewType;
    }

    public void setMViewType(int mViewType) {
        this.mViewType = mViewType;
    }
}
